### ISSUE TITLE
Level restrictions stopped working

### ISSUE THREAD

**Issue by vlad54rus** [Decane/SRP#105] opened 2020-04-23 10:27 UTC
Playing on latest SRP and just noticed that you can go to any other levels (Agroprom, Agr.Underground, Red Forest, Army Warehouses) right from the start without any restrictions.
![ss_Владислав_04-23-20_17-17-28_(military)](https://user-images.githubusercontent.com/22005398/80088886-5288d600-8587-11ea-91a1-4454eb86806a.jpg)

**Comment by Decane** [comment] 2020-04-23 12:02
I believe you can do that even in vanilla, as soon as you reach the Cordon?

**Comment by Decane** [comment] 2020-04-23 19:22
I just checked, and I am unable to leave the Swamps without a guide when my active task is "Go to the Cordon with the guide".

@vlad54rus
- Which level changer did you use to leave the Swamps?
- Did you start a new game?
- Are you using any other mods?
- Can you upload all the saves you made in the Swamps before leaving for another level?

**Comment by vlad54rus** [comment] 2020-04-24 09:49
I checked it again and now it worked as it should.
Currently i am playing on SRP + some config changes (weapon/ammo damage, psi-health restoration speed, demo_record camera speed) and for some reason all saves i made have unlocked level changers.
[savedgames.zip](https://github.com/Decane/SRP/files/4527806/savedgames.zip)

**Comment by Decane** [comment] 2020-04-24 17:08
@vlad54rus Thanks for the saves. A few questions (and some observations):

Is your 1.sav actually _a renamed autosave_ originally created while you were in conversation with Suslov?

The save's thumbnail, 1.dds, shows you having a conversation window open with Suslov. And the dialogue in the conversation window suggests you had just been given the starting equipment when the save was created.

Yet, when I load 1.sav, I have the starting equipment in my inventory. And if I then speak to Suslov, he offers me the starting equipment - a second time.

My guess is that your game auto-saved itself just when Suslov offered the starting equipment and the game got glitched by that somehow.

Do you remember anything unusual happening during that dialogue?

**Comment by SurDno** [comment] 2020-04-24 17:10
I've had thumbnail being very different from the actual place/moment I took a save, for reason unknown.

Can you take screenshot of dialogue history window? 

@vlad54rus, have you, by any chance, reproduced #79?

**Comment by SurDno** [comment] 2020-04-24 17:16
Leaving the dialogue early would not give the infoportion called **mar_intro_talk_with_guide_started** which would make it impossible to travel to Swamps since Trodnik would refuse to guide you unless you do what Lebedev says, so it's impossible to continue storyline even if something happened to the dialogue, intentionally or not.

**Comment by SurDno** [comment] 2020-04-24 17:18
Also, I just checked with Cheat Engine speedhack set to x500 speed, and autosave never happens while you're in the dialogue window, no matter how much time you spend in it. As soon as I closed it, I started getting autosaves normally.

**Comment by vlad54rus** [comment] 2020-04-24 17:30
> @vlad54rus, have you, by any chance, reproduced #79?
Yes i did, just to get more money early.

**Comment by Decane** [comment] 2020-04-24 17:43
@SurDno 

>I just checked with Cheat Engine speedhack set to x500 speed

I'm not sure that's a reliable way to test it. On the contrary, I'm pretty sure I once tested this by lowering the autosave interval in alife.ltx and then having a dialogue window open and autosaves happened mid-conversation. I even wrote a comment alluding to this possibility in task_manager.script, on the basis of my experiments:
```
An autosave while the player has the random task dialog open would erase the
entity IDs of any tasks of the aforementioned types that have by then been
allocated for player selection in that dialog by task_dialogs.squad_has_capture_tasks().
That would spell trouble, so this block is run only if the dialog window is closed.
```

**Comment by Decane** [comment] 2020-04-24 18:02
>Can you take screenshot of dialogue history window?

Not sure which of us this was addressed to, but here:

![Screenshot5259](https://user-images.githubusercontent.com/28687857/80242708-b087ed00-865d-11ea-8412-c92c0a1729df.png)

Notice how the dialogue history implies that the save was created before **vlad54rus** responded to Suslov giving him the equipment ("Thanks. Hey, is it always this stressful here?").

**Comment by SurDno** [comment] 2020-04-24 23:16
But does it matter if:
a) he already told you that he purposefully reproduced #79 to get more money early;
b) even if he did quit the dialogue early, there is no way he could then leave CS base so he had to finish the dialogue normally at least once anyway.

**Comment by vlad54rus** [comment] 2020-04-25 08:08
I guess i figured it out. For some reason system.ltx that i extracted from .db files and used to change camera properties was missing "script_binding = bind_level_changer.bind" in [level_changer] section. Probably because of wrong .db exctration order, so that is completly my fault and not SRP related.

**Closed** 2020-04-25 09:24 UTC
