### ISSUE TITLE
Log spam with open xray. (fix included)

### ISSUE THREAD

**Issue by LethalManBoob** [Decane/SRP#130] opened 2021-04-09 17:43 UTC
! [LUA]  CharacterCommunity available only for InventoryOwner
stack traceback:
	...mmon\stalker clear sky\gamedata\scripts\xr_danger.script:72: in function <...mmon\stalker clear sky\gamedata\scripts\xr_danger.script:38>

That looks like a benign error raised by danger_obj:character_community() when danger_obj can't be cast to a CInventoryOwner, which I presume is true of any non-creature entity, e.g. a grenade or sound. You might be able to get rid of it by modifying line 72 of xr_danger.script to be:
if IsStalker(danger_obj) and danger_obj:character_community() == self.faction then

edit: credit to github user Decane from openxray for finding this

**Comment by Decane** [comment] 2024-01-02 23:57
The reported error was caused by OpenXRay's incomplete Clear Sky compatibility when this issue was opened (explanation in [English](https://github.com/OpenXRay/xray-16/issues/768#issuecomment-816798125) / [Russian](https://github.com/OpenXRay/xray-16/issues/1253#issuecomment-1496769378)). This has since been addressed in https://github.com/OpenXRay/xray-16/commit/3dc9f5a846bf637b1f6091df60189c2120864a29, so the proposed work-around is no longer relevant.

**Closed by Decane** 2024-01-02 23:57 UTC
Labels: wontfix, invalid
