### ISSUE TITLE
The trader and technician at the Neutral base in Cordon have disappeared

### ISSUE THREAD

**Issue by BrainScorcher** [Decane/SRP#75] opened 2018-11-23 19:37 UTC
During a mutant attack on the base, all of the Loners disappeared. After the mutants were killed, the Loners in the courtyard returned to their places, but the trader (Shilov) & the technician (Van) have remained missing. There have been several attacks by mutants & bandits on the base since they were first noticed to have stayed away over a week or two of game time. As a result, I'm unable to collect the rewards they owe me.

Have not seen this behavior at any other bases.

**Comment by Decane** [comment] 2018-11-23 20:41
There's a good chance the issue you've described is a duplicate of #23, judging only by the symptoms. Try the fix I posted there and please let me know whether it works for you. If it doesn't, I'll need you to upload your savegame to be able to inspect the problem in more detail.

**Closed** 2018-11-23 21:55 UTC
Labels: duplicate
