### ISSUE TITLE
bandits turn red after capturing agroprom eastern outpost

### ISSUE THREAD

**Issue by nakanaki** [Decane/SRP#97] opened 2019-11-03 13:04 UTC
I don't know if it's a bug or not 
![20191103095351_1](https://user-images.githubusercontent.com/26018170/68085517-80832e00-fe20-11e9-9aaf-8ebbcd2905fc.jpg)
![20191103095401_1](https://user-images.githubusercontent.com/26018170/68085525-8da01d00-fe20-11e9-9ed3-f7471a3b3161.jpg)
![20191103100221_1](https://user-images.githubusercontent.com/26018170/68085571-0ef7af80-fe21-11e9-993b-33067463e11c.jpg)

**Comment by SurDno** [comment] 2019-11-03 14:41
See #33 and #89. 

TLDR: that’s the behavior developers intended, but it did not work in some cases. SRP ensures they’re always enemies to the player.

**Comment by Decane** [comment] 2019-11-03 15:55
@nakanaki

1. Which version of the SRP are you using in those screenshots?
2. Is it possible you did something to make that squad turn hostile?
3. Is it possible there are actually two squads at the position pointed to by your cursor in the 1st screenshot, and that the red squad icon in the 2nd screenshot is already present and red in the 1st, but is being obscured by the green icon?
4. Do you have a save from which to reproduce the sudden disposition change upon capture of the "Eastern outpost"?

**Comment by Decane** [comment] 2019-11-03 16:01
Yes, it's a bug. In configs\scripts\agroprom\agr_relation_stalker_base.ltx, we have:
```
[logic]
active = sr_idle@friend

[sr_idle@friend]
on_info = {=smart_captured_by_faction(agr_smart_terrain_4_4:stalker) =gulag_enemy_actor(agr_smart_terrain_4_4)} sr_idle@enemy %=set_gulag_relation_actor(agr_smart_terrain_4_4_near_1:enemy) =set_gulag_relation_actor(agr_smart_terrain_4_4_near_2:enemy) =set_gulag_relation_actor(agr_smart_terrain_4_4_near_3:enemy)%
on_info2 = {=smart_captured_by_faction(agr_smart_terrain_4_4_near_1:stalker) =gulag_enemy_actor(agr_smart_terrain_4_4_near_1)} sr_idle@enemy %=set_gulag_relation_actor(agr_smart_terrain_4_4:enemy) =set_gulag_relation_actor(agr_smart_terrain_4_4_near_2:enemy) =set_gulag_relation_actor(agr_smart_terrain_4_4_near_3:enemy)%
on_info3 = {=smart_captured_by_faction(agr_smart_terrain_4_4_near_2:stalker) =gulag_enemy_actor(agr_smart_terrain_4_4_near_2)} sr_idle@enemy %=set_gulag_relation_actor(agr_smart_terrain_4_4:enemy) =set_gulag_relation_actor(agr_smart_terrain_4_4_near_1:enemy) =set_gulag_relation_actor(agr_smart_terrain_4_4_near_3:enemy)%
on_info4 = {=smart_captured_by_faction(agr_smart_terrain_4_4_near_3:stalker) =gulag_enemy_actor(agr_smart_terrain_4_4_near_3)} sr_idle@enemy %=set_gulag_relation_actor(agr_smart_terrain_4_4:enemy) =set_gulag_relation_actor(agr_smart_terrain_4_4_near_1:enemy) =set_gulag_relation_actor(agr_smart_terrain_4_4_near_2:enemy)%

[sr_idle@enemy]
on_info = {!gulag_enemy_actor(agr_smart_terrain_4_4)} sr_idle@friend
on_info2 = {!gulag_enemy_actor(agr_smart_terrain_4_4_near_1)} sr_idle@friend
on_info3 = {!gulag_enemy_actor(agr_smart_terrain_4_4_near_2)} sr_idle@friend
on_info4 = {!gulag_enemy_actor(agr_smart_terrain_4_4_near_3)} sr_idle@friend
```
... where:
- agr_smart_terrain_4_4 = Stalker camp
- agr_smart_terrain_4_4_near_1 = Area next to the railroad platform
- agr_smart_terrain_4_4_near_2 = Backdoor exit
- agr_smart_terrain_4_4_near_3 = Eastern outpost

The logic says: 'If any of the four aforementioned camps is captured by stalkers and is hostile to the player, then make each of the other three camps hostile to the player, too.'

**Comment by Decane** [comment] 2019-11-03 16:03
Obviously, that logic is no good at all if the occupants of any of the other three camps are non-stalkers...

**Comment by Decane** [comment] 2019-11-03 16:13
The Duty base has similar logic in vanilla. Curiously, I spotted that and fixed it in the SRP at some point, but somehow overlooked that the Agroprom stalker base needed an equivalent fix.

**Comment by Decane** [comment] 2019-11-03 17:39
Fixed in commit https://github.com/Decane/SRP/commit/6e55f5a2e37e5c91e45cd5efa3ea38015c2f37b9.

**Note:** This fix prevents the bug from happening, but it will not 'correct' the disposition of any squad that has already become hostile due to the bug - it is not a retroactive fix.

**Closed by Decane** 2019-11-03 17:39 UTC
Labels: gameplay bug

**Comment by SurDno** [comment] 2019-11-04 01:18
But aren’t the bandits squads enemy by default anyway, as stated in #33?

**Comment by Decane** [comment] 2019-11-04 21:27
> But aren’t the bandits squads enemy by default anyway, as stated in #33?

The scripted squads that spawn in the tunnel are, yes. But the squad that is showing as green in **nakanaki**'s first screenshot is not a tunnel squad. I know this because there can only ever be one attacking tunnel squad at a time, and I see that squad in the same screenshot.
