### ISSUE TITLE
Duty won't take campment near embarkment after capture and hold

### ISSUE THREAD

**Issue by AlejandroBlanco** [Decane/SRP#82] opened 2019-02-17 05:45 UTC
After Duty members game me the capture mission of the campament near embankment (path from the swamps to the Agroprom institute) and I capture it, no Duty members will come to the swamps to hold this path. It is not possible to complete this mission. If there is something that triggered this behaviour I ignore it

**Comment by Decane** [comment] 2019-02-19 18:09
1. Did you receive the task via dialog?
2. Which version of the SRP are you using?

**Comment by Decane** [comment] 2019-02-19 18:30
BTW, the bug here is not that Duty won't move to the camp in the Swamps. This is by design: no squad is supposed to enter the Swamps from another map (the Swamps are isolated from other maps via sim_board.sim_level_cluster).

The bug is, rather, that Duty offered the task at all. I see that function sim_squad_generic:init_squad_task() is missing a check that would allow this to happen if the player asks a Duty squad at Agroprom's "Outpost by the hole" for work via dialog. I'll add the missing check...

**Comment by Decane** [comment] 2019-02-19 19:08
Fixed in f0d4265.

**Comment by AlejandroBlanco** [comment] 2019-02-19 19:50
Answering your question, I'm using SRP 1.1.2 and it was given via dialog.

So, the problem is they give a mission to enter in Swamps when there is a
switch that prevents them to enter in Swamps. Such a buggy game

**Comment by AlejandroBlanco** [comment] 2019-02-19 19:53
I can understand that if I copypaste the new script the mission won't
dissapear. I'll leave the buggy mission then till completition of game

**Closed** 2019-02-19 19:59 UTC
Labels: gameplay bug
