### ISSUE TITLE
Non random crash in Red Forest and Army Warehouses

### ISSUE THREAD

**Issue by bojan96** [Decane/SRP#124] opened 2021-02-11 10:54 UTC
How to reproduce: 
- Load attached [save file](https://github.com/Decane/SRP/files/5964713/red.forest.crash.zip)
- After save file is loaded wait for ~41 seconds (Or walk around red forest)
- After ~41 seconds game crashes to desktop.

What I noticed is that this crash happens after ~41 second passes from loading save file. 
Most of the time I can notice that crashes are random but this one is easy to reproduce.

Optional features used:
- Widescreen patch
- Alternative Ballistics

Version: v1.1.3-rc3

**Comment by bojan96** [comment] 2021-02-11 11:14
It seems that this issue is related to this save being quick save, I made a normal save several minutes before attached save and crash does not happen. I found quick saves to work most of the time so I used them(but readme says to avoid them).

**Comment by bojan96** [comment] 2021-02-11 11:38
Crash seems not to be related to quick saving. After I loaded working save file from red forest I went to army warehouses. There I made several normal saves along the way. I went to mercenary who gave me task (assaulting army warehouses with freedom).
I was normal saving frequently. After clearing army warehouses from enemy boys I made a normal save. After that save game crashes also after ~41 seconds idling. Here is the [save](https://github.com/Decane/SRP/files/5964931/warehouses.crash.zip).

**Comment by bojan96** [comment] 2021-02-11 11:55
Here is the [crash report](https://github.com/Decane/SRP/files/5965002/XRayEngine_error_report_210211-125000.zip)

**Comment by Decane** [comment] 2021-02-11 13:56
I reproduced the reported crash by loading the save in the OP and waiting as advised:
```
! [LUA][ERROR] Abort(): [sim_board.iterate_point]: Path between 'red_smart_terrain_monsters' and 'mil_smart_terrain_2_10' does not exist for squad with ID '26'.
 
stack traceback:
	_g.script:51: in function 'abort'
	sim_board.script:152: in function 'iterate_point'
	sim_board.script:816: in function 'find_path'
	sim_squad_generic.script:697: in function 'get_next_action'
	sim_squad_generic.script:542: in function 'update'
	se_monster.script:235: in function <se_monster.script:230>
```
This issue is a duplicate of https://github.com/Decane/SRP/issues/101, where I've also posted a [solution](https://github.com/Decane/SRP/issues/101#issuecomment-569499026).

**Closed by Decane** 2021-02-11 13:56 UTC
Labels: crash, duplicate, regression

**Comment by bojan96** [comment] 2021-02-11 14:15
That fixed the issue, thank you for quick response
