### ISSUE TITLE
Eliminate The Military at the Elevator not Triggering

### ISSUE THREAD

**Issue by Atryx10** [Decane/SRP#144] opened 2022-08-27 18:27 UTC
After talking to the commander in the cell at the Loner camp, talking to the leader of the camp should make the PDA update with the mission of eliminating the military at the Elevator, but nothing happens, and if you go to where the mission location should be, then there's also no military to kill, making it literally impossible to progress the story.

**Comment by Atryx10** [comment] 2022-08-27 18:48
Edit: I think the issue arose much earlier than this, as reloading a manual save done at the start of Cordon, and trying to leave the area, I got blocked because a transmission wasn't finished, so I think everything story related got blocked because I saved when Sidorovich was greeting you to Cordon, when you arrive near the military outpost.

**Comment by Atryx10** [comment] 2022-08-27 20:26
Edit 2: Yep, appears that saving in the middle of the Transmission breaks the mission system.

**Comment by Decane** [comment] 2022-08-28 11:49
Can you please upload all of your saves starting with the autosave created when you entered the Cordon?

If saving during Sid's PDA transmission were breaking the storyline, you would never even receive the task to reach the stalker base.

**Comment by Atryx10** [comment] 2022-08-28 13:37
Which is what happened, but I absolutely didn't notice, and everything was working as it should've up until the point it needed to spawn in npcs, whereupon everything being borked when it came to the storyline reared its head.
I sadly deleted my saves that were part of the "timeline" wherein the mission system got borked, as I was quite frustrated with losing out on about 40 minutes of gameplay and seeing that just restarting from the autosave and not doing a save until after the transmission made everything work as it should.

Btw, I also recently found an issue with when the Neutral Village in the Cordon gets attacked by mutants. At first, the game crashed when I was talking with the trader and started trading after having killed the mutants. The second time, the game crashed when I went to talk with the trader, and just before I started talking with them, the transmission about the Neutral Village being under attack from mutants began.

**Comment by Atryx10** [comment] 2022-08-28 13:58
Edit: Well, I'm confused now about why the game stopped responding the first time around. Maybe it was related to me getting "forced" to holster my weapons or smt as I was still inside the place when the fight was over? Surely it couldn't have been because the mutants in question were Flesh, right?

Anyways, here's my autosave at the start of the Cordon, and a manual one inside the Neutral Village shortly before the place gets attacked by mutants.

**Comment by Decane** [comment] 2022-08-29 08:23
Please avoid reporting multiple defects per issue; it makes it difficult to keep track of them. The crash while talking to the trader was probably [this one](https://github.com/Decane/SRP/blob/6ee4738bce3aeb92e2a259730c10e94323104f6a/SRP%20v1.1.4%20-%20Version%20History.txt#L10), which has been fixed for v1.1.4.

I was unable to replicate the bug you originally reported using my own saves. Since yours got deleted, there's no way for me to debug it.

I'll keep this issue open since this is a vanilla bug that's been reported multiple times over the years in various forums.

Examples: [#1](https://www.reddit.com/r/stalker/comments/huhwe9/clear_sky_main_quest_not_visible/), [#2](https://steamcommunity.com/app/20510/discussions/0/2796124181020741709/), [#3](https://gamefaqs.gamespot.com/boards/942067-stalker-clear-sky/45424935)

**Comment by Atryx10** [comment] 2022-08-29 11:39
Alright, sorry for doing that, will do better!
Btw, it might've been that as the task to enter the cordon was completed, the mission system didn't give the "talk to sidorovich" mission, and I was awaiting a new mission to be created after Sidorovich's transmission, but since that never happened, the transmission might've been seen as never having ended or something similar.

**Comment by Decane** [comment] 2023-11-12 22:59
The root cause of this bug has been discovered and resolved in https://github.com/Decane/SRP/issues/154.

**Closed by Decane** 2023-11-12 22:59 UTC
Labels: task bug
