### ISSUE TITLE
Visual glitches during rain

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#2] opened 2018-03-27 22:31 UTC
When it started raining in Escape, there were lots of strange visual glitches happening. See pics for some of them:
![ss_ _03-27-18_23-30-33_ escape](https://user-images.githubusercontent.com/35204405/37998159-34e7a1be-3226-11e8-921a-5eaa536ad208.jpg)
![ss_ _03-27-18_23-26-58_ escape](https://user-images.githubusercontent.com/35204405/37998181-4f06f43c-3226-11e8-87d2-b7316cba96a2.jpg)
![ss_ _03-27-18_23-27-04_ escape](https://user-images.githubusercontent.com/35204405/37998137-23070a7a-3226-11e8-8b6d-844b1701152c.jpg)
It works absolytely fine in any level with clear weather and during rain in any earlier save. I have never met such a bug in vanilla and rain happened to me multiple times during this playthrough (everything was normal), so I guess it's not something videocard related or just a glitch that can be fixed by F9. I attached the savefile (latest ModDB version, 1.12, I guess?), so you can reproduce this bug.
Due to GitHub not supporting .sav, here's the savefile: yadi.sk/d/Qz2HNks23TphSK

GTX 1080 Ti, every graphic setting maxed, installed everything optional from SRP, but 'No emissions' and SweetFX.

**Comment by Decane** [comment] 2018-03-28 13:43
This is a known intermittent vanilla glitch. From the "Bugs still in the game" section of the SRP readme:

>• Graphical artifacts may appear when it rains. Restart the game to work around this.

You can see it in action in [this early YouTube video from 2008](https://www.youtube.com/watch?v=nawa1i79vTM), right after Clear Sky's initial release, and before the SRP was created. According to one of the video comments, the glitch also afflicts SoC.

It seems to happen only when (but not whenever) reloading a savegame without first exiting the game. And it manifests only during rain. If the engine does shader caching, the glitch might be caused by the shader cache not getting flushed properly across reloads, but that's just speculation on my part - I don't know anything about the game's rendering engine.

I also don't know if it happens only on specific hardware - I've seen it with both my old HD4870 _and_ current GTX 1060.

**Comment by SurDno** [comment] 2018-03-28 14:22
Oh, I've just never met it before. 
What's interesting, in COP 1.6.01 patch changelog:
* Fixed graphical artifacts during rain.
Maybe if you examine the patch a little, you can find a solution.

**Comment by Decane** [comment] 2019-01-29 21:58
As we now know thanks to @Xottab_DUTY, this is an engine bug, not a shader bug. And it was indeed fixed in CoP by former GSC graphics programmer Armen Abroyan. The fix is to change the `if` statement on line 50 of xray-master\cs\engine\layers\xrRender\ResourceManager_Reset.cpp into an `else if` statement.

As it's an engine bug, it's beyond the scope of the SRP to fix, so I'm closing this.

**Closed by Decane** 2019-01-29 21:58 UTC
Labels: help wanted, shader bug

**Comment by Xottab-DUTY** [comment] 2019-01-30 18:39
Here's the visual diff:
![unknown](https://user-images.githubusercontent.com/2989212/52004011-efc19f80-24e7-11e9-9028-d12fb0f4953f.png)
Left is Clear Sky, right is Call of Pripyat.
