### ISSUE TITLE
Giving Private Lambee a pistol with no ammo results in him eternally running from player

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#28] opened 2018-10-20 14:30 UTC
When you get to the underroad bridge on Escape (the one near the wagon where you met Tolik in SoC), you can find private Lambee (Ovechko), who may ask you for a gun to 'go rescue mayor Khaletskiy'. However, as soon as you give him a pistol, he betrays and kills you for some reason (_first few years of playing this game I thought this was a bug :D_).
![20181019145826_1](https://user-images.githubusercontent.com/35204405/47256688-c2973700-d48c-11e8-9a61-57a824d3bee5.jpg)
However, when given a gun with no ammo, he just starts running away through all the Escape and yelling ''**DON'T SHOOT, STALKER, PLEASE, DON'T SHOOT**'' unless killed by either anomalies, or loners.

**Comment by Marek33** [comment] 2018-10-20 14:48
This is a classic behavior of any hostile NPC in the S.T.A.L.K.E.R. series, if they don't have an ammo for the gun. So, I'm not sure, if this should count as a bug.

**Comment by SurDno** [comment] 2018-10-20 15:54
The problem of private Lambee is that, while usual NPCs usually can always reload their weapons if the weapon had _at least one_ bullet when they picked it up, Lambee usually just shoots his first magazine and then runs. Or runs immediately after picking up the gun if there was no ammo originally.
If Khaletskiy is given a gun with no ammo, he just continues sitting on his place, so it's possible to hold him from eternal unnecessary running.

**Comment by Marek33** [comment] 2018-10-20 17:32
Yes, that's also the classic behavior of the S.T.A.L.K.E.R. NPCs. I'm using the Moddb version v1.1.2 and when I give a weapon with no ammo to the Khaletskiy, he managed to escape from the base, but also continues sitting on the unnamed camp right outside the original stalker base. I'm not sure how its called, but it's the one, where are sometimes wild dogs, which will eventually kill him, unless he gets a better weapon. However, it's weird, that he doesn't move to the outpost, since he is a major.

**Comment by SurDno** [comment] 2018-10-20 18:54
I guess in vanilla game he just disappeared without a trace, without getting to outpost or spawning anythere else.

**Comment by SurDno** [comment] 2018-10-20 22:39
Hehe. You really miss something, because when you had to wait several minutes of game loading because it had crashed from dying in an anomaly, artifact hunting was much more dangerous. 🗡 

I started playing CS years before I learned about SRP and, yeah, the game could really break in any minute.

**Comment by Decane** [comment] 2018-10-25 20:04
I like that the player can one-up Lambee's deception by giving him a pistol with an empty magazine. Him turning hostile at that point and running away also seems to approximate the right behavior; the real life equivalent would be him attempting to shoot you, only to have the pistol make a 'click' sound, and then cowardly fleeing upon realizing that his duplicity has been exposed.

The problem is, there is no explicit animation of / attempt at him shooting the player if he lacks ammo for the gun, so his immediately turning hostile and fleeing upon receiving the weapon can confuse and appear 'buggy' to a new player who isn't aware of how this sequence usually plays out and hence is unable to interpret Lambee's reaction correctly.

I _could_ spawn pistol ammo of every type into Lambee's inventory to enable him to shoot at the player regardless of initial ammo presence in the pistol, but that would eliminate the possibility of the player turning the tables on him, which I think is a consequence I dislike even more than the fact that Lambee behaves so erratically when given an empty pistol.

Maybe I should tweak his logic so he always points the pistol at the player for a second or two before attempting to use it?

**Comment by Marek33** [comment] 2018-10-25 21:38
@Decane Yes, that would be very interesting to see.

**Comment by SurDno** [comment] 2018-10-25 23:32
Ho-ho, I did not try to look at this situation from that point of view. That... kind of makes sense now.

That idea of pointing pistol is very good, I would like to see it in-game. Giving ammo via script seems like a good workaround though if at some point you realize you can not tweak his logic. 

If there's no animation of his attempt of shooting the player, maybe you can make him point his pistol for a few secs and then play no-ammo sound independently? You can use the one player hears when his weapon.

This cutscene seems so interesting to see I'd rather have this behavior even when player gives Lambee a pistol with ammo... But such things are clearly beyond scope of SRP, I suppose.

**Comment by Decane** [comment] 2018-11-04 15:30
Looks like making an NPC aim an empty pistol at the player is not supported. A work-around I have implemented -- but have not pushed yet -- is to have Lambee attempt to punch the player after he is given a pistol. (The player can dodge the punch if he is fast enough.) Lambee then tries to empty the pistol into the player and flees thereafter. Or, if the pistol was empty already, Lambee flees immediately after taking the swing. Thoughts?

**Comment by Marek33** [comment] 2018-11-04 16:32
@Decane I would prefer if he would first punch the player to slow us down, and then start fleeing. He still could be killed easily, but it would make more sense for him, to punch, instead of being hostile and starting running like a lunatic.

**Comment by SurDno** [comment] 2018-11-04 19:18
Maybe you can give him some ammo if pistol is already empty and make him point his gun without shooting the player? Bandits robbing player at Garbage can aim at the player, though I don’t know if they would not have an ability to do this if they have no ammo left.
If choosing between those two variants, punching then fleeing seems like the best variant.

**Comment by Decane** [comment] 2019-01-19 16:14
Addressed in 6d676d6: to make Lambee's deception more obvious, he now tries to punch the player before attacking / fleeing. He will still "eternally run", though, once he runs out of ammo. I have no intention of 'fixing' that at this time, for the reason articulated earlier.

**Closed by Decane** 2019-01-19 16:14 UTC
