### ISSUE TITLE
No description for 7.62x54 ammo

### ISSUE THREAD

**Issue by nytak619** [Decane/SRP#84] opened 2019-03-11 19:57 UTC
Ammo for 7.62x54 7h1 lack description ingame.

NO real name weapons mod was installed

**Comment by nytak619** [comment] 2019-03-11 20:14
Lazy solution - add same text description as in vanilla game into 
gamedata\configs\text\rus

**Comment by SurDno** [comment] 2019-03-11 20:41
Duplicate of #12

**Closed** 2019-03-11 21:14 UTC
Labels: duplicate
