### ISSUE TITLE
 Sidorovich after bringing his swag makes a lifetime discount on goods, but not for the entire range

### ISSUE THREAD

**Issue by JIuBeP** [Decane/SRP#43] opened 2018-11-10 16:05 UTC
Sidorovich after bringing his swag makes a lifetime discount on goods, but not for the entire range. Is this intended? For example winchester (chaser 13) all also has a price markup of 3 times.

**Comment by JIuBeP** [comment] 2018-11-10 17:43
hmm... about chaser 13 it seems I was wrong, as the range discount updated a little later.

**Comment by Decane** [comment] 2018-11-11 10:58
In the English translation, Sid's promise to the player is:

>I’m extending you a lifetime store discount

It's not clear whether "store discount" is meant to imply a discount across his entire range of stock. The following items are not discounted:

- AKS-74
- PKM
- Leather Jacket
- Bandit Jacket
- Tourist's Delight
- Vodka
- "Echo" Detector
- All pre-upgraded armors and weapons

I have no way to tell what was intended here, so I won't fiddle with it.

About the discount not taking effect immediately: after Sid informs the player of the discount, it should take effect on the next 'use' of the trader by the player after closing his dialog window. If you don't exit the dialog window before going into the trade screen with Sid after he promises the discount, it won't yet have been applied. This is a limitation of the way trade supply updates are handled in the SRP - [see my GSC forum post](https://www.gsc-game.com/main.php?t=community&s=forums&s_game_type=xr&thm_page=1&thm_id=11786&page=338&sort=ASC&sec_id=16#410756) for details.

**Closed by Decane** 2018-11-11 10:58 UTC
