### ISSUE TITLE
'Heading' line in PDA may not display where the squad is actually heading

### ISSUE THREAD

**Issue by SurDno** [Decane/SRP#56] opened 2018-11-19 00:06 UTC
Sometimes it's just like showing one point (usually the one needed by current expansion) and then going to another one. However, this, funnily, may include:

-  The point the squad came from (Bandits going to Depot):

![image](https://user-images.githubusercontent.com/35204405/48680001-ab408c00-eba7-11e8-884c-e823270aac31.png)

- The point occupied by friendly faction (Loners going to Duty Base):

![image](https://user-images.githubusercontent.com/35204405/48680016-e216a200-eba7-11e8-9ad4-953a31ea5ea4.png)

- The point literraly impossible to capture (`sim_avail = false`) (Monolith going to Stalker's Camp):

![image](https://user-images.githubusercontent.com/35204405/48680039-17bb8b00-eba8-11e8-8990-dca2819012f8.png)

**Comment by Decane** [comment] 2019-03-24 19:06
Should be mostly fixed since commit d89a652, mainly thanks to its edits to sim_faction.script:489 and sim_squad_generic.script:1594-1596.

However, squads can still suddenly change their mind about which smart terrain to move to while already on their way to one, thereby rendering the initial squad target tooltip text inaccurate post-hoc. This is by design, and is not possible to 'fix' without completely re-writing the squad target selection system.

Speculatively closing in light of the first paragraph, but feel free to re-open this issue if the tooltip target still seems inaccurate after commit d89a652, bearing in mind the caveat in the second paragraph above.

**Closed by Decane** 2019-03-24 19:06 UTC
Labels: interface bug

**Comment by SurDno** [comment] 2019-07-15 01:42
Yay, late reply, but still.

I might miss how you fixed it, but I seem to find the actual root of the problem. 

So, after playing Build 3436 (20 days prior to release for a while), I've noticed that instead of heading tab, there was much more debug information. This included 'target' and 'attack_point' as different sections. Seems like target is where the squad is going overall and attack_point is the point he is going to capture right now.
![image](https://user-images.githubusercontent.com/35204405/61192082-6deeb880-a6ba-11e9-88f8-8f1394b8f65e.png)

Since this little boar squad never reached Red Forest, and dies during its first attempt at clearing the road, the player might think that the target is being displayed wrong when it is actually not. More of a bad design decision than an actual bug.

Is it possible to switch Heading tab from showing 'target' to showing 'attack_point'?

**Comment by Decane** [comment] 2019-07-27 15:17
@SurDno

You can enable similar debug info in the SRP's version of sim_squad_generic.script by searching for "DEBUG INFO:" and uncommenting the code beneath both instances of it.

>Is it possible to switch Heading tab from showing 'target' to showing 'attack_point'?

I contemplated doing this a couple of years back, but ultimately decided against it because it's not the feature GSC wanted to implement. Also, I think it's of questionable value to print a moving squad's immediate target, since most of the time that's discernible just by opening the map and seeing which camp is closest to their present location.
