### ISSUE TITLE
Duty NPCs getting stuck at right staircase of main building

### ISSUE THREAD

**Issue by eqagunn** [Decane/SRP#94] opened 2019-07-02 15:55 UTC
NPCs on the stairs are stuck there, while those below stay there willingly.
My character also breathes heavily while standing close to them.

Sometimes after save reload, those down below run out of the building.
And those stuck on the stairs, walk down through the floor, climb up through the floor again and then continue down the stairs normally.

![ss_matz-laptop_07-02-19_15-21-23_(agroprom)](https://user-images.githubusercontent.com/25494031/60527439-192a6580-9cea-11e9-94fb-d3afcf94ebc7.jpg)
![ss_matz-laptop_07-02-19_15-22-44_(agroprom)](https://user-images.githubusercontent.com/25494031/60527445-1cbdec80-9cea-11e9-80f8-dd5d8decc027.jpg)

**Comment by Decane** [comment] 2019-07-28 10:19
Duplicate of #64.

**Closed by Decane** 2019-07-28 10:19 UTC
Labels: duplicate, gameplay bug
